/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.*;
import java.text.*;
import java.util.Date;
import javax.swing.*;

public class ThemPKBFrm extends javax.swing.JFrame {

    ArrayList<String> ListMaBS = new ArrayList<String>();
    ArrayList<String> ListTenBS = new ArrayList<String>();
    public void LoadCbbTenBS()
    {
        Connection con= new ConnectDB().createConn();
        try{
            String strSQL="Select* from BacSi";
            Statement stat= con.createStatement();
            ResultSet rs =stat.executeQuery(strSQL);
            while(rs.next())
            {
                ListMaBS.add(rs.getString("MaBS"));
                ListTenBS.add(rs.getString("TenBS"));
            }
        }
        cbbTenBS.setModel(new DefaultComboBoxModel<String>(ListTenBS.toArray(new String[0])));
        catch(SQLException e)
        {
           System.out.println(e);
           System.out.println("Lỗi");
        }
    }
    public String LayMaKB()
    {
        String MaKB="";
        Connection con= new ConnectDB().createConn();
        String strSQL="select MaKB from khambenh order by MaKB DESC";
        try
        {
           Statement stat= con.createStatement();
           ResultSet rs =stat.executeQuery(strSQL);
        
        if(rs.absolute(1)==false)
        {
            MaKB="KB0001";
        }
        else
        {
            String MaKBHienTai=rs.getString("MaKB");
            MaKB=MaKBHienTai.substring(2,6);
            int MaKBmoi=Integer.parseInt(MaKB)+1;
            if(MaKBmoi<10)
            {
                MaKB="KB000"+MaKBmoi;
                
            }
            else
                if(MaKBmoi<1000)
                    MaKB="KB0"+MaKBmoi;
                else
                    MaKB="KB"+MaKBmoi;
           
        }
        con.close();    
        }
        catch(Exception e)
        {
            e.printStackTrace();
            System.out.println("Lỗi");
        }
         return MaKB;      
    }
            
   
    public ThemPKBFrm() {
        initComponents();
        setTitle("Đặt lịch khám");
        Date date=new Date();
        datNgKham.setDate(date);
        txtTenBN.setEditable(false);
        LoadCbbTenBS();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMaBN = new javax.swing.JLabel();
        lblTenBN = new javax.swing.JLabel();
        lblNgKham = new javax.swing.JLabel();
        lblYeuCauKham = new javax.swing.JLabel();
        lblTenBS = new javax.swing.JLabel();
        txtMaBN = new javax.swing.JTextField();
        txtTenBN = new javax.swing.JTextField();
        txtYeuCauKham = new javax.swing.JTextField();
        datNgKham = new com.toedter.calendar.JDateChooser();
        cbbTenBS = new javax.swing.JComboBox<>();
        btnDatLichKham = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMaBN.setText("Mã bệnh nhân");

        lblTenBN.setText("Tên bệnh nhân");

        lblNgKham.setText("Ngày khám");

        lblYeuCauKham.setText("Yêu cầu khám");

        lblTenBS.setText("Bác sĩ khám");

        txtMaBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaBNActionPerformed(evt);
            }
        });

        cbbTenBS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnDatLichKham.setText("Đặt lịch khám");
        btnDatLichKham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLichKhamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMaBN, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(lblYeuCauKham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNgKham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTenBN, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(lblTenBS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaBN)
                    .addComponent(txtTenBN)
                    .addComponent(txtYeuCauKham)
                    .addComponent(datNgKham, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(cbbTenBS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(btnDatLichKham, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaBN)
                    .addComponent(txtMaBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenBN)
                    .addComponent(txtTenBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNgKham)
                    .addComponent(datNgKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYeuCauKham)
                    .addComponent(txtYeuCauKham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenBS)
                    .addComponent(cbbTenBS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnDatLichKham, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatLichKhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLichKhamActionPerformed
       if(txtMaBN.getText().equals("")|| txtYeuCauKham.getText().equals(""))           
       {
           JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin","Thông báo",JOptionPane.INFORMATION_MESSAGE);
       }
       else
       {
           Date nowdate=new Date();
           DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
           if(df.format(nowdate).compareTo(df.format(datNgKham.getDate()))>0)
             JOptionPane.showMessageDialog(null, "Ngày khám phải >= Ngày hiện tại","Thông báo",JOptionPane.INFORMATION_MESSAGE);
           else
           {
              Connection con= new ConnectDB().createConn();
              String strSQL="insert into KHAMBENH(MaKB,MaBN,MaBS,NGAYKHAM,YEUCAUKHAM,THANHTOAN) VALUES(?,?,?,?,?,0";
              try
              {
                  PreparedStatment pres=con.prepareStatement
              }
                  
                    
           }
                       
       }
                  
                   
                   
    }//GEN-LAST:event_btnDatLichKhamActionPerformed

    private void txtMaBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaBNActionPerformed
        Connection con = new ConnectDB().createConn();
        String strSQL="Select * from BENHNHAN where MABN ='"+txtMaBN.getText()+"'";
        try
        {
            Statement stat =con.createStatement();
            ResultSet rs =stat.executeQuery(strSQL);
            if(rs.absolute(1)==false)
            {
                JOptionPane.showMessageDialog(null, "Không tìm thấy bệnh nhân!","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                txtTenBN.setText("");
                txtMaBN.setText("");
       
            }
            else
                {
                    txtTenBN.setText((rs.getString("TenBN")));
                }
            con.close();
            
        }
        catch(Exception e){
            e.printStackTrace();
            System.out.println("Lỗi");
        }
                   
    }//GEN-LAST:event_txtMaBNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemPKBFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemPKBFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemPKBFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemPKBFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemPKBFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatLichKham;
    private javax.swing.JComboBox<String> cbbTenBS;
    private com.toedter.calendar.JDateChooser datNgKham;
    private javax.swing.JLabel lblMaBN;
    private javax.swing.JLabel lblNgKham;
    private javax.swing.JLabel lblTenBN;
    private javax.swing.JLabel lblTenBS;
    private javax.swing.JLabel lblYeuCauKham;
    private javax.swing.JTextField txtMaBN;
    private javax.swing.JTextField txtTenBN;
    private javax.swing.JTextField txtYeuCauKham;
    // End of variables declaration//GEN-END:variables
}
